### ISSUE TITLE
CI support

### ISSUE THREAD

**Issue by izgzhen** [izgzhen/sl-tut-iris#1]

**Comment by swr1bm86** [comment]
Hi @izgzhen, I have some trouble building this project, after `make iris-local`, everything goes fine. But if I use `make`, it will complain `Cannot find a physical path bound to logical path matching suffix` error which I struggled for a while.

![image](https://cloud.githubusercontent.com/assets/6234553/20585362/a69dc1a2-b235-11e6-87b8-74fcad35d215.png)

Travis also unhappy with building it for the same reason, the build log is [here](https://travis-ci.org/zjhmale/sl-tut-iris/builds/178351995).

**Comment by izgzhen** [comment]
First, very sorry that I forgot to update the `Makefile` to match our latest design. I will soon update it.

Second, glad to see you have interest in this project :) In fact, I was trying to port https://gitlab.mpi-sws.org/FP/iris-atomic/blob/master/.gitlab-ci.yml to travis CI yesterday, but didn't have enough time/experience so just submitting an issue reminding me to do it later. Very sorry that I didn't post more information in the issue body. You can take the gitlab ci example as a reference if needed. I guess I won't be able to do it better than you :P

**Comment by izgzhen** [comment]
Done. BTW, the reason why the mismatched `Makefile` doesn't work is that local `iris` is not linked to `iris-enabled`. In `_CoqProject`, the `-Q` specifies that we can use `iris-enabled` (i.e. local Iris) to build project. But there is a small unpleasant thing that the way to switch to the global Iris dependency is simply deleting this symbolic link. So `coqc` will fall back to the global PATH automatically. This is somewhat a hack ...

**Comment by swr1bm86** [comment]
@izgzhen Great, thanks for the prompt catch-up, I can kindly build it now!

I just walked by and see this great project, separation logic and iris are fascinating, hope I can contribute to some chapters soon :)
>glad to see you have interest in this project

I can see the hack on `iris-atomic` , currently, I'm not an expert on Coq system, so it really tangled me for a while last night 😅 .
>This is somewhat a hack ...
